<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="barista_bot">

<xacro:include filename="$(find barista_robot_description)/xacro/wheel.xacro" />
<!-- <xacro:include filename="$(find barista_robot_description)/xacro/standoff.xacro" /> -->

<!-- Color -->
<material name="red">
    <color rgba="1.0 0.0 0.0 1"/>
</material>

<material name="green_light">
    <color rgba="0.0 1.0 0.0 1"/>
</material>

<material name="green_dark">
<color rgba="0.0 0.5 0.0 1"/>
</material>

<material name="blue">
    <color rgba="0.0 0.0 1.0 1"/>
</material>

<material name="black">
    <color rgba="0.0 0.0 0.0 1"/>
</material>

<material name="box_bot_blue">
    <color rgba="0.088656 0.428691 0.491021 1"/>
</material>


<!-- Dimension Parameters -->
<xacro:property name="base_width" value="0.356"/>
<xacro:property name="base_height" value="0.155"/>

<xacro:property name="cup_tray_width" value="0.32"/>
<xacro:property name="cup_tray_height" value="0.09"/>


<xacro:property name="wheel_width" value="0.001"/>
<xacro:property name="wheel_radius" value="0.035"/>

<!-- Base Link -->
<link name="base_link">
  </link>

<!-- Cylinder Base -->
<link name="chassis">
<visual>
    <geometry>
    <cylinder length="${base_height}" radius="${base_width/2}"/>
    </geometry>
    <material name="blue"/>
</visual>

<inertial>
    <mass value="0.2"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <inertia ixx="0.0019846" ixy="0" ixz="0" iyy="0.0019846" iyz="0" izz="0.0031684"/>
</inertial>

<collision>
    <geometry>
    <cylinder length="${base_height}" radius="${base_width/2}"/>
    </geometry>
</collision>

</link>

<joint name="base_link_joint" type="fixed">
<origin rpy="0 0 0" xyz="0 0 0" />
<parent link="base_link" />
<child link="chassis" />
</joint>

<!-- Wheel Macro -->
<xacro:wheel wheel_name="left_wheel"/>

<joint name="joint_left_wheel" type="continuous">
    <origin rpy="0 0 0" xyz="0 0.128 -0.0775"/>
    <child link="left_wheel"/>
    <parent link="chassis"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
</joint>

<xacro:wheel wheel_name="right_wheel"/>
<joint name="joint_right_wheel" type="continuous">
    <origin rpy="0 0 0" xyz="0 -0.128 -0.0775"/>
    <child link="right_wheel"/>
    <parent link="chassis"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
</joint>

<!--  -->


</robot>