<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="barista_bot">

<xacro:include filename="$(find barista_robot_description)/xacro/wheel.xacro" />
<xacro:include filename="$(find barista_robot_description)/xacro/standoff.xacro" />
<xacro:include filename="$(find barista_robot_description)/xacro/cup_holder_tray.xacro" />

<!-- Color -->
<material name="red">
    <color rgba="1.0 0.0 0.0 1"/>
</material>

<material name="green_light">
    <color rgba="0.0 1.0 0.0 1"/>
</material>

<material name="green_dark">
<color rgba="0.0 0.5 0.0 1"/>
</material>

<material name="blue">
    <color rgba="0.0 0.0 1.0 1"/>
</material>

<material name="black">
    <color rgba="0.0 0.0 0.0 1"/>
</material>

<material name="box_bot_blue">
    <color rgba="0.088656 0.428691 0.491021 1"/>
</material>


<!-- Dimension Parameters -->
<xacro:property name="base_width" value="0.356"/>
<xacro:property name="base_height" value="0.155"/>

<xacro:property name="cup_tray_width" value="0.32"/>
<xacro:property name="cup_tray_height" value="0.09"/>


<xacro:property name="wheel_width" value="0.001"/>
<xacro:property name="wheel_radius" value="0.035"/>

<!-- Base Link -->
<link name="base_link">
  </link>

<!-- Cylinder Base -->
<link name="chassis">
<visual>
    <geometry>
    <cylinder length="${base_height}" radius="${base_width/2}"/>
    </geometry>
    <material name="blue"/>
</visual>

<inertial>
    <mass value="0.2"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <inertia ixx="0.0019846" ixy="0" ixz="0" iyy="0.0019846" iyz="0" izz="0.0031684"/>
</inertial>

<collision>
    <geometry>
    <cylinder length="${base_height}" radius="${base_width/2}"/>
    </geometry>
</collision>

</link>

<joint name="base_link_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0" />
    <parent link="base_link" />
    <child link="chassis" />
</joint>

<!-- Wheel Macro -->
<xacro:wheel wheel_name="left_wheel"/>

<joint name="joint_left_wheel" type="continuous">
    <origin rpy="0 0 0" xyz="0 0.128 -0.0775"/>
    <child link="left_wheel"/>
    <parent link="chassis"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
</joint>

<xacro:wheel wheel_name="right_wheel"/>
<joint name="joint_right_wheel" type="continuous">
    <origin rpy="0 0 0" xyz="0 -0.128 -0.0775"/>
    <child link="right_wheel"/>
    <parent link="chassis"/>
    <axis rpy="0 0 0" xyz="0 1 0"/>
    <limit effort="10000" velocity="1000"/>
    <joint_properties damping="1.0" friction="1.0"/>
</joint>

<!-- Standoff -->
<xacro:standoff standoff_name="standoff_rod_front_left"/>
<joint name="standoff_rod_FL_to_chassis_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0.05 0.12 0.1875" />
    <parent link="chassis" />
    <child link="standoff_rod_front_left" />
</joint>

<xacro:standoff standoff_name="standoff_rod_back_left"/>
<joint name="standoff_rod_BL_to_chassis_joint" type="fixed">
    <origin rpy="0 0 0" xyz="-0.05 0.12 0.1875" />
    <parent link="chassis" />
    <child link="standoff_rod_back_left" />
</joint>

<xacro:standoff standoff_name="standoff_rod_front_right"/>
<joint name="standoff_rod_FR_to_chassis_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0.05 -0.12 0.1875" />
    <parent link="chassis" />
    <child link="standoff_rod_front_right" />
</joint>

<xacro:standoff standoff_name="standoff_rod_back_right"/>
<joint name="standoff_rod_BR_to_chassis_joint" type="fixed">
    <origin rpy="0 0 0" xyz="-0.05 -0.12 0.1875" />
    <parent link="chassis" />
    <child link="standoff_rod_back_right" />
</joint>

<!-- Cup Tray -->
<xacro:cup_holder cup_holder_name="cup_tray"/>
<joint name="cup_tray_to_chassis_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0.3425" />
    <parent link="chassis" />
    <child link="cup_tray" />
</joint>

<!-- Caster Wheels -->
   <!-- yaw -->
  <link name="front_yaw_link">
    <visual>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.005" radius="0.0352"/>
        </geometry>
        <material name="blue"/>
    </visual>

    <inertial>
      <mass value="0.01"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.0000031184" ixy="0" ixz="0" iyy="0.0000031184" iyz="0" izz="0.000006195"/>
    </inertial>

    <collision>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.005" radius="0.0352"/>
        </geometry>
    </collision>
  </link>

    <gazebo reference="front_yaw_link">
    <kp>1000000000000000000000000000.0</kp>
    <kd>1000000000000000000000000000.0</kd>
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>
  </gazebo>

  <joint name="front_yaw_joint" type="continuous">
    <origin rpy="0 0 0" xyz="0.12 0 -0.0775" />
    <parent link="chassis" />
    <child link="front_yaw_link" />
    <axis xyz="0 0 1" />
    <limit effort="1000.0" velocity="100.0" />
    <dynamics damping="0.0" friction="0.1"/>
  </joint>

<!-- roll -->
  <link name="front_roll_link">
      <visual>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.005" radius="0.0352"/>
        </geometry>
        <material name="red"/>
      </visual>

    <inertial>
      <mass value="0.01"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.0000031184" ixy="0" ixz="0" iyy="0.0000031184" iyz="0" izz="0.000006195"/>
    </inertial>

    <collision>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.005" radius="0.0352"/>
        </geometry>
    </collision>
  </link>

    <gazebo reference="front_roll_link">
    <kp>1000000000000000000000000000.0</kp>
    <kd>1000000000000000000000000000.0</kd>
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>
  </gazebo>

  <joint name="front_roll_joint" type="continuous">
    <origin rpy="0 0 0" xyz="0 0 0" />
    <parent link="front_yaw_link" />
    <child link="front_roll_link" />
    <axis xyz="1 0 0" />
    <limit effort="1000.0" velocity="100.0" />
    <dynamics damping="0.0" friction="0.1"/>
  </joint>

<!-- pitch -->
  <link name="front_pitch_link">
    <visual>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.0352"/>
      </geometry>
      <material name="green_dark"/>
    </visual>

    <inertial>
      <mass value="0.01"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.00000826" ixy="0" ixz="0" iyy="00.00000826" iyz="0" izz="0.00000826"/>
    </inertial>

    <collision>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.0352"/>
      </geometry>
    </collision>
  </link>

    <gazebo reference="front_pitch_link">
    <kp>1000000000000000000000000000.0</kp>
    <kd>1000000000000000000000000000.0</kd>
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>
    <material>Gazebo/Purple</material>
  </gazebo>

  <joint name="front_pitch_joint" type="continuous">
    <origin rpy="0 0 0" xyz="0 0 0" />
    <parent link="front_roll_link" />
    <child link="front_pitch_link" />
    <axis xyz="0 1 0" />
    <limit effort="1000.0" velocity="100.0" />
    <dynamics damping="0.0" friction="0.1"/>
  </joint>


<!-- Caster Wheel Back -->
  <link name="back_yaw_link">
    <visual>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.005" radius="0.0352"/>
        </geometry>
        <material name="blue"/>
      </visual>

    <inertial>
      <mass value="0.01"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.0000031184" ixy="0" ixz="0" iyy="0.0000031184" iyz="0" izz="0.000006195"/>
    </inertial>

    <collision>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.005" radius="0.0352"/>
        </geometry>
    </collision>
  </link>

    <gazebo reference="back_yaw_link">
    <kp>1000000000000000000000000000.0</kp>
    <kd>1000000000000000000000000000.0</kd>
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>
  </gazebo>

  <joint name="back_yaw_joint" type="continuous">
    <origin rpy="0 0 0" xyz="-0.12 0 -0.0775" />
    <parent link="chassis" />
    <child link="back_yaw_link" />
    <axis xyz="0 0 1" />
    <limit effort="1000.0" velocity="100.0" />
    <dynamics damping="0.0" friction="0.1"/>
  </joint>



  <link name="back_roll_link">
      <visual>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.005" radius="0.0352"/>
        </geometry>
        <material name="red"/>
      </visual>

    <inertial>
      <mass value="0.01"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.0000031184" ixy="0" ixz="0" iyy="0.0000031184" iyz="0" izz="0.000006195"/>
    </inertial>

    <collision>
        <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
        <geometry>
          <cylinder length="0.005" radius="0.0352"/>
        </geometry>
    </collision>
  </link>

  <gazebo reference="back_roll_link">
    <kp>1000000000000000000000000000.0</kp>
    <kd>1000000000000000000000000000.0</kd>
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>
  </gazebo>

  <joint name="back_roll_joint" type="continuous">
    <origin rpy="0 0 0" xyz="0 0 0" />
    <parent link="back_yaw_link" />
    <child link="back_roll_link" />
    <axis xyz="1 0 0" />
    <limit effort="1000.0" velocity="100.0" />
    <dynamics damping="0.0" friction="0.1"/>
  </joint>



  <link name="back_pitch_link">
    <visual>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.0352"/>
      </geometry>
      <material name="green_light"/>
    </visual>

    <inertial>
      <mass value="0.01"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.00000826" ixy="0" ixz="0" iyy="00.00000826" iyz="0" izz="0.00000826"/>
    </inertial>

    <collision>
      <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
      <geometry>
        <sphere radius="0.0352"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="back_pitch_link">
    <kp>1000000000000000000000000000.0</kp>
    <kd>1000000000000000000000000000.0</kd>
    <mu1>0.1</mu1>
    <mu2>0.1</mu2>
    <material>Gazebo/Yellow</material>
  </gazebo>

  <joint name="back_pitch_joint" type="continuous">
    <origin rpy="0 0 0" xyz="0 0 0" />
    <parent link="back_roll_link" />
    <child link="back_pitch_link" />
    <axis xyz="0 1 0" />
    <limit effort="1000.0" velocity="100.0" />
    <dynamics damping="0.0" friction="0.1"/>
  </joint>


<!-- Laser -->
<xacro:arg name="include_laser" default="true"/>

<xacro:if value="$(arg include_laser)">
    <!-- Laser Link -->
    <link name="laser_scan_link">
        <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry> 
            <mesh filename="package://barista_robot_description/meshes/hokuyo_urg_04lx.dae" scale="1.0 1.0 1.0"/>
        </geometry>
        </visual>

        <collision>
        <origin rpy="0 0 0" xyz="0 0 0.0204"/>
        <geometry>
            <box size="0.074986 0.074935 0.0408"/>
        </geometry>
        </collision>

        <inertial>

        <mass value="0.01"/>
        <origin rpy="0 0 0" xyz="0 0 0.0204"/>
        <inertia ixx="6.066578520833334e-06" ixy="0" ixz="0" iyy="6.072950163333333e-06" iyz="0" izz="9.365128684166666e-06"/>
        </inertial>
    </link>

    <joint name="laser_scan_link_joint" type="fixed">
        <origin rpy="0 0 0" xyz="0.0 0.0 0.0775"/>
        <parent link="chassis"/>
        <child link="laser_scan_link"/>
    </joint>

    <link name="laser_scan_frame">
    </link>

    <joint name="laser_scan_frame_joint" type="fixed">
        <origin rpy="0 0 0" xyz="0 0 0.03"/>
        <parent link="laser_scan_link"/>
        <child link="laser_scan_frame"/>
        <axis xyz="0 0 0"/>
    </joint>

<!-- Laser -->
<gazebo reference="laser_scan_frame">
    <sensor name="sensor_ray" type="ray">
        <pose>0 0 0 0 0 0</pose>
        <ray>
          <scan>
            <horizontal>
              <samples>200</samples>
              <resolution>1.0</resolution>
              <min_angle>-3.14</min_angle>
              <max_angle>3.14</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.1</min>
            <max>5.0</max>
          </range>
        </ray>
        <always_on>true</always_on>
        <visualize>true</visualize>
        <update_rate>100.0</update_rate>
        <plugin name="laser" filename="libgazebo_ros_ray_sensor.so">
          <ros>
            <namespace>/barista_bot</namespace>
            <remapping>~/out:=laser_scan</remapping>
          </ros>
          <output_type>sensor_msgs/LaserScan</output_type>
        </plugin>
    </sensor>
</gazebo>

</xacro:if>



</robot>