<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="barista_bot">

<!-- Color -->
<material name="red">
    <color rgba="1.0 0.0 0.0 1"/>
</material>

<material name="green_light">
    <color rgba="0.0 1.0 0.0 1"/>
</material>

<material name="green_dark">
<color rgba="0.0 0.5 0.0 1"/>
</material>

<material name="blue">
    <color rgba="0.0 0.0 1.0 1"/>
</material>

<material name="black">
    <color rgba="0.0 0.0 0.0 1"/>
</material>

<material name="white">
    <color rgba="1.0 1.0 1.0 1"/>
</material>

<material name="box_bot_blue">
    <color rgba="0.088656 0.428691 0.491021 1"/>
</material>


<!-- Dimension Parameters -->
<xacro:property name="base_width" value="0.356"/>
<xacro:property name="base_height" value="0.155"/>

<xacro:property name="standoff_height" value="0.22"/>
<xacro:property name="standoff_diameter" value="0.02"/>

<xacro:property name="cup_tray_width" value="0.32"/>
<xacro:property name="cup_tray_height" value="0.09"/>


<xacro:property name="wheel_width" value="0.001"/>
<xacro:property name="wheel_radius" value="0.035"/>

<!-- Base Link -->
<link name="base_link">
  </link>

<!-- Cylinder Base -->
<link name="chassis">
<visual>
    <geometry>
    <cylinder length="${base_height}" radius="${base_width/2}"/>
    </geometry>
    <material name="blue"/>
</visual>

<inertial>
    <mass value="0.2"/>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <inertia ixx="0.0019846" ixy="0" ixz="0" iyy="0.0019846" iyz="0" izz="0.0031684"/>
</inertial>

<collision>
    <geometry>
    <cylinder length="${base_height}" radius="${base_width/2}"/>
    </geometry>
</collision>

</link>

<joint name="base_link_joint" type="fixed">
<origin rpy="0 0 0" xyz="0 0 0" />
<parent link="base_link" />
<child link="chassis" />
</joint>

</robot>