<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- RVIZ Color -->
<material name="white">
    <color rgba="1.0 1.0 1.0 1"/>
</material>

<!-- Parameters -->
<xacro:property name="standoff_height" value="0.22"/>
<xacro:property name="standoff_diameter" value="0.02"/>

<!-- Standoff Macro -->
<xacro:macro name="standoff" params="standoff_name">
  <link name="${standoff_name}">   
    <visual>
        <geometry>
            <cylinder length="${standoff_height}" radius="${standoff_diameter/2}"/>
        </geometry>
        <material name="white"/>
    </visual>

    <collision>
        <geometry>
            <cylinder length="${standoff_height}" radius="${standoff_diameter/2}"/>
        </geometry>
    </collision>

    <inertial>
      <mass value="0.02"/>
      <inertia ixx="0.00008117" ixy="0" ixz="0" iyy="0.00008117" iyz="0" izz="0.000001"/>
    </inertial>

  </link>

</xacro:macro>
    
</robot>   